on:
  [ workflow_dispatch, push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Print nix version
        uses: workflow/nix-shell-action@v3.4.0
        with:
          flakes-from-devshell: true
          script: |
            echo "here is the node version" && node --version
            

